### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wangzi815** [r9y9/VoiceConversion.jl#7] opened 2015-07-17 05:27 UTC
HI,thanks for sharing.now i have  a problem:
ERROR: `pygmmcovar2jl` has no method matching pygmmcovar2jl(::PyObject)
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading ~/.julia/v0.3/VoiceConversion/scripts/train_gmm.jl, in expression starting on line 106
can you help me?

**Comment by wangzi815** [comment] 2015-07-17 07:27
![1](https://cloud.githubusercontent.com/assets/13376067/8742457/2a2e4674-2c98-11e5-99b0-0fdb3000ae92.png)
Ubuntu 14.04 32bit

**Comment by r9y9** [comment] 2015-07-17 07:37
Oh, thanks for reporting the problem. I will have a look later today. Could you elaborate on what commands you tried?

**Comment by wangzi815** [comment] 2015-07-17 07:44
Pkg.clone("https://github.com/r9y9/MelGeneralizedCepstrums.jl")
Pkg.clone("https://github.com/r9y9/SynthesisFilters.jl") 
Pkg.clone("https://github.com/r9y9/VoiceConversion.jl")

**Comment by wangzi815** [comment] 2015-07-17 07:47
julia 0.3.8 or julia 0.3.10,the result is the same:pygmmcovar2jl has no method matching pygmmcovar2jl(::PyObject)

**Comment by r9y9** [comment] 2015-07-19 12:38
I could not reproduce the problem on ubuntu 14.04 64bit. `pygmmcovar2jl` is only used in `train_gmm.jl` and I don't think the file is loaded while cloning. So I guess you got the error when you tried some commands after installation?

If the problem happens in train_gmm.jl, it might be a compatibility issue with  `sklearn.mixture`, which I use in training GMMs.

**Comment by wangzi815** [comment] 2015-07-20 06:08
Thank you very much for replying.You are very responsible for the voiceconversion project.
I try it on  ubuntu 14.04 64bit,comparing to ubuntu 14.04 32bit ,the problem does not appear.But i do not  know what the reason yet，i just try 64 bit system,and redo the commands.Can you  elaborate on what the real reason cause this problem? Maybe some library require 64 bit system?

**Comment by r9y9** [comment] 2015-07-20 07:48
I'm not sure what the real reason is, since I could not reproduce the problem :(

I have win32 testing passed (see https://github.com/r9y9/VoiceConversion.jl/pull/8), so I guess the problem is unrelated to bits of systems.

**Comment by r9y9** [comment] 2015-09-12 08:52
I will close this. Feel free to reopen this if you have the same problem.

**Closed by r9y9** 2015-09-12 08:52 UTC
